version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    expose:
      - 80
    volumes:
      - ./audiobookshelf/audiobooks:/audiobooks
      - ./audiobookshelf/podcasts:/podcasts
      - ./audiobookshelf/config:/config
      - ./audiobookshelf/metadata:/metadata
    env_file:
      - .env.dev
    networks:
      - proxy

  reverse-proxy:
    image: nginx:latest
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx/certs:/etc/ssl/audiobook
      - ./nginx/conf:/etc/nginx
    networks:
      - proxy
    env_file:
      - .env.dev
    depends_on:
      - audiobookshelf

networks:
  proxy:
